from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
driver = webdriver.Firefox()

url= 'https://demoqa.com/webtables'
driver.maximize_window()
driver.get(url)

driver.find_element(By.ID, 'addNewRecordButton').click()
driver.find_element(By.ID, 'firstName').click()
driver.find_element(By.ID, 'firstName').send_keys("Nurul")
driver.find_element(By.ID, 'lastName').click()
driver.find_element(By.ID, 'lastName').send_keys("Fatma")
driver.find_element(By.ID, 'userEmail').click()
driver.find_element(By.ID, 'userEmail').send_keys("nurfa.qatest@gmail.com")
driver.find_element(By.ID, 'age').click()
driver.find_element(By.ID, 'age').send_keys("24")
driver.find_element(By.ID, 'salary').click()
driver.find_element(By.ID, 'salary').send_keys("90000000")
driver.find_element(By.ID, 'department').click()
driver.find_element(By.ID, 'department').send_keys("Digital Transformation")
driver.find_element(By.ID, 'submit').click()
sleep(2)
driver.find_element(By.ID, 'addNewRecordButton').click()
driver.find_element(By.ID, 'firstName').click()
driver.find_element(By.ID, 'firstName').send_keys("Padma")
driver.find_element(By.ID, 'lastName').click()
driver.find_element(By.ID, 'lastName').send_keys("Ramadhani")
driver.find_element(By.ID, 'userEmail').click()
driver.find_element(By.ID, 'userEmail').send_keys("nurul@okadoc.com")
driver.find_element(By.ID, 'age').click()
driver.find_element(By.ID, 'age').send_keys("34")
driver.find_element(By.ID, 'salary').click()
driver.find_element(By.ID, 'salary').send_keys("10000000")
driver.find_element(By.ID, 'department').click()
driver.find_element(By.ID, 'department').send_keys("Technology")
driver.find_element(By.ID, 'submit').click()
sleep(2)
driver.find_element(By.ID, 'addNewRecordButton').click()
driver.find_element(By.ID, 'firstName').click()
driver.find_element(By.ID, 'firstName').send_keys("Sahira")
driver.find_element(By.ID, 'lastName').click()
driver.find_element(By.ID, 'lastName').send_keys("Damara")
driver.find_element(By.ID, 'userEmail').click()
driver.find_element(By.ID, 'userEmail').send_keys("dearyoumshopinc@gmail.com")
driver.find_element(By.ID, 'age').click()
driver.find_element(By.ID, 'age').send_keys("33")
driver.find_element(By.ID, 'salary').click()
driver.find_element(By.ID, 'salary').send_keys("190000000")
driver.find_element(By.ID, 'department').click()
driver.find_element(By.ID, 'department').send_keys("Operations")
driver.find_element(By.ID, 'submit').click()
sleep(2)

driver.close()